`orchestrator.ts` has been improved by:

1.  **Introducing Constants:** Replaced magic numbers with descriptive constants (`MAX_DEVELOPMENT_RETRIES`, `DEFAULT_APP_INPUT`) for better readability and maintainability.
2.  **Modularity with Helper Functions:** Extracted distinct stages of the orchestration into dedicated asynchronous helper functions (`executePlanningStage`, `executeDesigningStage`, `executeDevelopmentLoop`). This makes the main `runOrchestrator` function cleaner and easier to follow, acting as a high-level summary of the process.
3.  **Enhanced Logging:** Improved `console.log` messages for better clarity, progress tracking, and structured JSON output (using `JSON.stringify` for plan/design).
4.  **Robustness:** Added a top-level `try...catch` block in `runOrchestrator` to gracefully handle potential errors from any stage of the process, preventing unhandled crashes.
5.  **Flexibility:** Made the initial `input` an optional parameter for `runOrchestrator` with a default value, allowing for easier future expansion or programmatic invocation with different requirements.

These changes enhance readability, maintainability, and robustness without altering the core business logic or breaking existing functionality.

```typescript
// FILE: ./src/agents/designer.ts
import { callLLM } from "../utils/openai.js";
import { getHarnessPrinciples } from "../utils/harness-principles.js";

export async function designer(plan: any) {
  const principles = getHarnessPrinciples();
  const res = await callLLM(
    `You are a UI designer. Output JSON only.

Apply these harness engineering principles:
${principles}`,
    `
Plan:
${JSON.stringify(plan)}

Return:
{
  "components": [
    { "name": "", "props": [] }
  ]
}
`
  );

  return JSON.parse(res);
}

// FILE: ./src/agents/developer.ts
import { callLLM } from "../utils/openai.js";
import { getHarnessPrinciples } from "../utils/harness-principles.js";
import fs from "fs";

export async function developer(plan: any, design: any, feedback?: string) {
  const principles = getHarnessPrinciples();
  const res = await callLLM(
    `You are a frontend developer. Return code only.

Apply these harness engineering principles:
${principles}`,
    `
Plan:
${JSON.stringify(plan)}

Design:
${JSON.stringify(design)}

Feedback:
${feedback || "none"}

Generate a React Todo App (single file).
`
  );

  fs.mkdirSync("./artifacts", { recursive: true });
  fs.writeFileSync("./artifacts/App.tsx", res);

  return res;
}

// FILE: ./src/agents/index.ts
export { designer } from "./designer.js"
export { developer } from './developer.js'
export { planner} from './planner.js'
export { reviewer} from './reviewer.js'
export { tester} from './tester.js'
// FILE: ./src/agents/planner.ts
import { callLLM } from "../utils/openai.js";
import { getHarnessPrinciples } from "../utils/harness-principles.js";

export async function planner(input: string) {
  const principles = getHarnessPrinciples();
  const res = await callLLM(
    `You are a planner. Output JSON only.

Apply these harness engineering principles:
${principles}`,
    `
Create a plan for:
${input}

Return:
{
  "features": [],
  "acceptance_tests": []
}
`
  );

  return JSON.parse(res);
}

// FILE: ./src/agents/reviewer.ts
import { callLLM } from "../utils/openai.js";
import { getHarnessPrinciples } from "../utils/harness-principles.js";

export async function reviewer(logs: string) {
  const principles = getHarnessPrinciples();
  const res = await callLLM(
    `You analyze errors and suggest fixes.

Apply these harness engineering principles:
${principles}`,
    `
Error:
${logs}

Return:
{
  "issue": "",
  "fix": ""
}
`
  );

  return JSON.parse(res);
}

// FILE: ./src/agents/tester.ts
import fs from "fs";

export async function tester() {
  const code = fs.readFileSync("./artifacts/App.tsx", "utf-8");

  if (code.includes("useState")) {
    return { success: true };
  }

  return {
    success: false,
    logs: "useState not found"
  };
}
// FILE: ./src/orchestrator.ts
import { planner, designer, developer, tester, reviewer } from "./agents/index.js";

// --- Constants ---
const MAX_DEVELOPMENT_RETRIES = 5;
const DEFAULT_APP_INPUT = "React Todo App with CRUD";

// --- Helper Functions for Orchestration Stages ---

/**
 * Executes the planning stage.
 * @param input The user's request for the application.
 * @returns The plan generated by the planner agent.
 */
async function executePlanningStage(input: string) {
  console.log("🧠 Planning...");
  const plan = await planner(input);
  console.log("PLAN:", JSON.stringify(plan, null, 2)); // Pretty print JSON for better readability
  return plan;
}

/**
 * Executes the design stage.
 * @param plan The plan generated by the planner.
 * @returns The design generated by the designer agent.
 */
async function executeDesigningStage(plan: any) {
  console.log("\n🎨 Designing...");
  const design = await designer(plan);
  console.log("DESIGN:", JSON.stringify(design, null, 2)); // Pretty print JSON
  return design;
}

/**
 * Executes the core development and testing loop with retries.
 * @param plan The application plan.
 * @param design The application design.
 * @param maxRetries The maximum number of development attempts.
 * @returns true if development was successful within retries, false otherwise.
 */
async function executeDevelopmentLoop(plan: any, design: any, maxRetries: number) {
  let success = false;
  let retryCount = 0;
  let feedback = ""; // Feedback string for the developer agent

  while (!success && retryCount < maxRetries) {
    console.log(`\n💻 Development Attempt ${retryCount + 1}/${maxRetries}`);

    // Call the developer agent to generate code
    await developer(plan, design, feedback);

    console.log("🧪 Testing...");
    // Call the tester agent to evaluate the generated code
    const testResult = await tester();

    if (testResult.success) {
      console.log("✅ SUCCESS: Application developed and passed tests!");
      success = true;
      break; // Exit the loop on success
    }

    console.log(`❌ Test Failed (Attempt ${retryCount + 1}/${maxRetries})`);
    // If tests fail, get feedback from the reviewer agent
    const reviewLogs = testResult.logs || "Unknown test failure";
    const analysis = await reviewer(reviewLogs);

    // Format the feedback for the next development attempt
    feedback = `
Issue: ${analysis.issue}
Fix: ${analysis.fix}
`;
    console.log("Reviewer Feedback:", feedback);

    retryCount++;
  }

  if (!success) {
    console.log(`🚨 FAILED: Application could not be developed after ${maxRetries} retries.`);
  }

  return success;
}

/**
 * The main orchestration function.
 * @param input The desired application to be built.
 */
async function runOrchestrator(input: string = DEFAULT_APP_INPUT) {
  try {
    // Stage 1: Planning
    const plan = await executePlanningStage(input);

    // Stage 2: Designing
    const design = await executeDesigningStage(plan);

    // Stage 3: Development, Testing, and Review Loop
    const developmentSuccessful = await executeDevelopmentLoop(plan, design, MAX_DEVELOPMENT_RETRIES);

    if (developmentSuccessful) {
      console.log("\n✨ Orchestration Complete: Application successfully built!");
    } else {
      console.log("\n🚧 Orchestration Halted: Application failed to build within retries.");
    }
  } catch (error) {
    console.error("\n💥 Orchestration Error:", error);
    // In a real application, more specific error handling or cleanup might be needed here.
  }
}

// Start the orchestration process
runOrchestrator();

// FILE: ./src/utils/harness-principles.ts
import fs from "fs";

const PRINCIPLES_PATH = "./docs/HARNESS_PRINCIPLES.md";

export function getHarnessPrinciples() {
  try {
    return fs.readFileSync(PRINCIPLES_PATH, "utf-8");
  } catch {
    return "";
  }
}


// FILE: ./src/utils/openai.ts
import OpenAI from "openai";
import dotenv from "dotenv";

dotenv.config();

type LLMProvider = "openai" | "gemini";

const provider = (process.env.LLM_PROVIDER || "openai").toLowerCase() as LLMProvider;
const openAIModel = process.env.OPENAI_MODEL || "gpt-4o-mini";
const geminiModel = process.env.GEMINI_MODEL || "gemini-2.5-flash";

function requireEnv(name: string) {
  const value = process.env[name];
  if (!value) {
    throw new Error(
      `Missing ${name}. Set it in .env to use ${provider.toUpperCase()} provider.`
    );
  }
  return value;
}

function createOpenAIClient() {
  const apiKey = requireEnv("OPENAI_API_KEY");
  return new OpenAI({ apiKey });
}

async function callOpenAI(system: string, user: string) {
  const client = createOpenAIClient();
  const res = await client.chat.completions.create({
    model: openAIModel,
    messages: [
      { role: "system", content: system },
      { role: "user", content: user }
    ],
    temperature: 0.3
  });

  const content = res.choices[0]?.message?.content;
  if (!content) {
    throw new Error("OpenAI returned an empty response.");
  }

  return content;
}

async function callGemini(system: string, user: string) {
  const apiKey = requireEnv("GEMINI_API_KEY");
  const url =
    `https://generativelanguage.googleapis.com/v1beta/models/` +
    `${geminiModel}:generateContent?key=${apiKey}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      systemInstruction: {
        parts: [{ text: system }]
      },
      contents: [
        {
          role: "user",
          parts: [{ text: user }]
        }
      ],
      generationConfig: {
        temperature: 0.3
      }
    })
  });

  if (!response.ok) {
    const message = await response.text();
    throw new Error(`Gemini API request failed: ${response.status} ${message}`);
  }

  const data = await response.json();
  const text = data?.candidates?.[0]?.content?.parts
    ?.map((part: { text?: string }) => part.text || "")
    .join("") || "";

  if (!text) {
    throw new Error("Gemini returned an empty response.");
  }

  return text;
}

export async function callLLM(system: string, user: string) {
  if (provider === "gemini") {
    return callGemini(system, user);
  }

  if (provider === "openai") {
    return callOpenAI(system, user);
  }

  throw new Error(
    `Unsupported LLM_PROVIDER "${provider}". Use "openai" or "gemini".`
  );
}
```